/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsDefault = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
  docs: [
    {
      type: 'category',
      label: 'Guides',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Docs',
          items: ['analytics/analytics', 'api-overview/api-contract',],
        },
      ],
    },
  ],
  accounts: [
    {
      type: "category",
      label: "Account Management",
      link: {
        type: "generated-index",
        title: "Account Management API",
        description:
            "This is a sample server Account Management server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/accountmanagement"
      },
      // @ts-ignore
      items: require("./docs/api/accountmanagement/sidebar.js")
    },
  ],
  exporter: [
    {
      type: "category",
      label: "Exporter",
      link: {
        type: "generated-index",
        title: "Exporter API",
        description:
            "This is a sample server Account Management server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/exporter"
      },
      // @ts-ignore
      items: require("./docs/api/exporter/sidebar.js")
    },
  ],
  flows: [
    {
      type: "category",
      label: "Flows",
      link: {
        type: "generated-index",
        title: "Flows API",
        description:
            "This is a sample server Account Management server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/flows"
      },
      // @ts-ignore
      items: require("./docs/api/flows/sidebar.js")
    },
  ],
  integrations: [
    {
      type: "category",
      label: "Integrations",
      link: {
        type: "generated-index",
        title: "Integrations API",
        description:
            "This is a sample server Account Management server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/integrations"
      },
      // @ts-ignore
      items: require("./docs/api/integrations/sidebar.js")
    },
  ],
  payments: [
    {
      type: "category",
      label: "Payments",
      link: {
        type: "generated-index",
        title: "Payments API",
        description:
            "This is a sample server Account Management server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/payments"
      },
      // @ts-ignore
      items: require("./docs/api/payments/sidebar.js")
    },
  ],
  promotions: [
    {
      type: "category",
      label: "Promotions",
      link: {
        type: "generated-index",
        title: "Promotions API",
        description:
            "This is a sample server Account Management server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/promotions"
      },
      // @ts-ignore
      items: require("./docs/api/promotions/sidebar.js")
    },
  ],
  pxm: [
    {
      type: "category",
      label: "Product Information Manager",
      link: {
        type: "generated-index",
        title: "Product Information Manager API",
        slug: "/pxm/products"
      },
      // @ts-ignore
      items: require("./docs/api/pxm/pim/sidebar.js")
    },
      //Price Books
    {
      type: "category",
      label: "Price Books",
      link: {
        type: "generated-index",
        title: "Price Books API",
        slug: "/pxm/pricebooks"
      },
      // @ts-ignore
      items: require("./docs/api/pxm/pricebooks/sidebar.js")
    },
    //Catalog
    {
      type: "category",
      label: "Catalog",
      link: {
        type: "generated-index",
        title: "Catalog API",
        slug: "/pxm/catalog"
      },
      // @ts-ignore
      items: require("./docs/api/pxm/catalog/sidebar.js")
    },
      //Inventory
    {
      type: "category",
      label: "Inventory",
      link: {
        type: "generated-index",
        title: "Inventory API",
        slug: "/pxm/inventory"
      },
      // @ts-ignore
      items: require("./docs/api/pxm/inventory/sidebar.js")
    },
    {
      type: "category",
      label: 'API Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-overview',
        },
      ]
    },
    {
      type: 'category',
      label: 'Includes',
      items: ['pxm/includes'],
    },
  ],
  subscriptions: [
    {
      type: "category",
      label: "Subscriptions",
      link: {
        type: "generated-index",
        title: "Subscriptions API",
        description:
            "This is for the service overview section. Feel free to use any way you wish.",
        slug: "/subscriptions"
      },
      // @ts-ignore
      items: require("./docs/api/subscriptions/sidebar.js")
    },
    {
      type: "category",
      label: 'API Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-overview',
        },
      ]
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

};

module.exports = sidebarsDefault;
